#!/usr/bin/env python3
"""Build the single autonomous S8 OMNI production frontend bundle."""

from __future__ import annotations

import argparse
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
FRONTEND = ROOT / "custom_components" / "s8_omni" / "frontend"
OUTPUT = FRONTEND / "s8-omni-production.js"
BASE = FRONTEND / "s8-omni-panel.js"
EXTENSIONS = (
    FRONTEND / "s8-omni-cleaning-presets.js",
    FRONTEND / "s8-omni-service-settings.js",
    FRONTEND / "s8-omni-preset-live-highlight.js",
    FRONTEND / "s8-omni-panel-bootstrap.js",
)
STATIC_IMPORT_RE = re.compile(r"(?m)^\s*import\s+[\"'][^\"']+[\"'];\s*$")
DYNAMIC_IMPORT_RE = re.compile(r"\bimport\s*\(")


def read_source(path: Path) -> str:
    return path.read_text(encoding="utf-8").rstrip()


def extension_body(path: Path) -> str:
    source = read_source(path)
    if path.name == "s8-omni-panel-bootstrap.js":
        imports = STATIC_IMPORT_RE.findall(source)
        if len(imports) != 4:
            raise SystemExit(f"expected four bootstrap imports, found {len(imports)}")
        source = STATIC_IMPORT_RE.sub("", source).strip()
    if STATIC_IMPORT_RE.search(source) or DYNAMIC_IMPORT_RE.search(source):
        raise SystemExit(f"runtime import remains in build source: {path.name}")
    return source


def build_text() -> str:
    source_names = [BASE.name, *(path.name for path in EXTENSIONS)]
    parts = [
        "// Generated by scripts/build_s8_production.py. Do not edit directly.",
        f"// Sources: {', '.join(source_names)}",
        "",
        read_source(BASE),
    ]
    for path in EXTENSIONS:
        parts.extend(
            [
                "",
                f"/* source: {path.name} */",
                "(() => {",
                extension_body(path),
                "})();",
            ]
        )
    result = "\n".join(parts).rstrip() + "\n"
    if STATIC_IMPORT_RE.search(result) or DYNAMIC_IMPORT_RE.search(result):
        raise SystemExit("generated production bundle contains a runtime import")
    return result


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail unless committed output is current")
    args = parser.parse_args()

    expected = build_text()
    if args.check:
        if not OUTPUT.is_file():
            raise SystemExit(f"missing generated bundle: {OUTPUT.relative_to(ROOT)}")
        current = OUTPUT.read_text(encoding="utf-8")
        if current != expected:
            raise SystemExit("s8-omni-production.js is not reproducible from current build sources")
        print("S8 production bundle is current and autonomous")
        return

    OUTPUT.write_text(expected, encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
